In [1]:
%pip install -q numpy
import numpy as np

%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
class Matrix:
    matrix: list = [[1, 2, 5],
    [4, 55, 4],
    [25, 0, 7]]
    
    def __init__(self, matrix = [[1, 2, 5],
    [4, 55, 4],
    [25, 0, 7]]):
        if matrix is not None:
            self.matrix = matrix

    def __len__(self):
        return len(self.matrix)    
    
    def __add__(self, other: list | int | float):
        m_summ = [[] for x in self.matrix]
        if type(other) == int or type(other) == float:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    summ = self.matrix[row_num][column_num] + other
                    m_summ[row_num].append(summ)
        elif type(other.matrix) == list:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    summ = self.matrix[row_num][column_num] + other.matrix[row_num][column_num]
                    m_summ[row_num].append(summ)
        return m_summ
    
    def __sub__(self, other: list | int | float):
        m_sub = [[] for x in self.matrix]
        if type(other) == int or type(other) == float:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    sub = self.matrix[row_num][column_num] - other
                    m_sub[row_num].append(sub)
        elif type(other.matrix) == list:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    sub = self.matrix[row_num][column_num] - other.matrix[row_num][column_num]
                    m_sub[row_num].append(sub)
        return m_sub
    
    def __mul__(self, other: list | int | float):
        m_mul = [[] for x in self.matrix]
        if type(other) == int or type(other) == float:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    mul = self.matrix[row_num][column_num] * other
                    m_mul[row_num].append(mul)
        elif type(other.matrix) == list:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    mul = self.matrix[row_num][column_num] * other.matrix[row_num][column_num]
                    m_mul[row_num].append(mul)
        return m_mul
    
    def __truediv__(self, other: list | int| float):
        m_truediv = [[] for x in self.matrix]
        if type(other) == int or type(other) == float:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    truediv = self.matrix[row_num][column_num] / other
                    m_truediv[row_num].append(truediv)
        elif type(other.matrix) == list:
            for row_num, row in enumerate(self.matrix):
                for column_num, digit in enumerate(row):
                    truediv = self.matrix[row_num][column_num] / other.matrix[row_num][column_num]
                    m_truediv[row_num].append(truediv)
        return m_truediv
    
    def T(self, other = None):
        if other != None:
            transposing_m = other.matrix
        else:
            transposing_m = self.matrix
        transpose_frame = []
        t_column_quantity = len(transposing_m)
        t_row_quantity = len(transposing_m[0])
        for rows in range(t_row_quantity):
            sub_list = []
            for number in range(t_column_quantity):
                sub_list.append(number)
            transpose_frame.append(sub_list) # Создаем каркас транспонированной матрицы с производными числами внутри
        for row_num, row in enumerate(transposing_m):
                for column_num, digit in enumerate(row):
                    transpose_frame[column_num][row_num] = digit # Заменяем производные числа на правильные
        return transpose_frame
    
    def __matmul__(self, other: list):
        if len(other.matrix) > len(self.matrix):
            other.matrix = self.T(other)
        scalar_frame = []
        for rows in range(len(self.matrix)):
            sub_list = []
            for number in range(len(other.matrix[0])):
                sub_list.append(number)
            scalar_frame.append(sub_list) # каркас для результата скалярного произведения
        for row_num, row in enumerate(scalar_frame):
                for column_num, digit in enumerate(row):
                    one_result = 0
                    for i in range(len(other.matrix)):
                        x = self.matrix[row_num][i] * other.matrix[i][column_num]
                        one_result += x
                    scalar_frame[row_num][column_num] = one_result
        return scalar_frame
    



In [3]:
%%ipytest

matrix1 = Matrix(matrix=[
    [6, 1, 13],
    [6, 6, 0],
    [1555, 2, 1]
])
matrix2 = Matrix(matrix=[
    [7, 1, 44],
    [7, 7, 8],
    [11, 12, -11]
])

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T() == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

..........                                                                                   [100%]
10 passed in 0.02s


In [8]:
matrix1 = Matrix(matrix=[
    [6, 1, 13],
    [6, 6, 0],
    [1555, 2, 1]
])
matrix2 = Matrix(matrix=[
    [7, 1, 44],
    [7, 7, 8],
    [11, 12, -11]
])

matrix1 @ matrix2, np.array(matrix1.matrix) @ np.array(matrix2.matrix)

([[192, 169, 129], [84, 48, 312], [10910, 1581, 68425]],
 array([[  192,   169,   129],
        [   84,    48,   312],
        [10910,  1581, 68425]]))

In [5]:
m1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])
m2 = Matrix(
    matrix=[
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
]
)

f = m1+m2
f

[[5, 6, 7], [8, 10, 12], [88, 24, 25], [13, 23, 78]]

In [6]:
npmatrix1 = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33]

])

npmatrix2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
])
z = npmatrix1 + npmatrix2
z

array([[ 5,  6,  7],
       [ 8, 10, 12],
       [88, 24, 25],
       [13, 23, 78]])

In [7]:
f == z

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])