In [2]:
#torch - библиотека для работы с тензорами
import torch
import torch.nn as nn

In [14]:
#Инициализация вектора
a = torch.IntTensor([1, 1, 2, 3, 4])
b = torch.IntTensor([1, 1, 4, 5, 6])
a*b

tensor([ 1,  1,  8, 15, 24], dtype=torch.int32)

In [13]:
c = torch.tensor([1, 1, 2, 3, 4])
c

tensor([1, 1, 2, 3, 4])

In [15]:
torch.dot(a, b)

tensor(49, dtype=torch.int32)

In [22]:
a = torch.rand((1, 4)) #цифры показывают размерность
b = torch.rand((4, 1))
a

tensor([[0.9586, 0.3386, 0.3295, 0.8991]])

In [23]:
a@b

tensor([[0.4268]])

In [24]:
a.shape #размерность через атрибут
a.size() #тоже размерность но методом

torch.Size([1, 4])

In [26]:
a[None, :].shape
#Добавляет размерность, сохраняя при этом изначальные значения
a

tensor([[0.9586, 0.3386, 0.3295, 0.8991]])

In [28]:
a.view(-1, 1).shape #-1 в данном случае равно 4

torch.Size([4, 1])

In [29]:
a.T

tensor([[0.9586],
        [0.3386],
        [0.3295],
        [0.8991]])