In [12]:
%pip install -q numpy 
#-quite тихая установка

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 1, 1, 0, 0, 1])
#answ=[0, 2, 3, 0, 0, 6]
# У array нет аттрибута append

In [15]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
a*b

array([0, 2, 3, 0, 0, 6])

In [14]:
c = np.array([
    [1, 2, 3],
    [3, 2, 1],
])
c.T

array([[1, 3],
       [2, 2],
       [3, 1]])

In [16]:
a @ b

11

In [18]:
a.dot(b)
#Скалярное произвеление

11